### ISSUE TITLE
Remove the Term tag

### ISSUE THREAD

**Issue by MeMeBallJM** [StorageTechDictionary/StorageTechDictionary.github.io#1]
Everything which the dictionary defines is a term. I personally suggest the Term tag being removed.
<img width="593" alt="Screen Shot 2022-08-12 at 2 40 41 PM" src="https://user-images.githubusercontent.com/91382906/184423201-260f6274-723f-4df1-8ebd-b0d2aee8dda0.png">

**Comment by Firigion** [comment]
We can maybe rename it? Not sure to what, tho. Or if it's necessary at all.

**Comment by JoakimThorsen** [comment]
I think it could be removed for some entries, but I'm not sure you can really remove it for things like "binary" or "encoded" "locational"? Not sure, though addition of more tags definitely won't hurt.

**Comment by MeMeBallJM** [comment]
> We can maybe rename it? Not sure to what, tho. Or if it's necessary at all.

I think it might make sense to rename the tag to "concept".

Going off of google definitions here's the difference:

Term: a word or phrase used to describe a thing or to express a concept, especially in a particular kind of language or branch of study.

Concept: an abstract idea; a general notion.

From what I tell the current usage of the tag seems to be for ideas.

**Comment by JoakimThorsen** [comment]
I messed up some github logs/commit messages, but I've fixed this in f998dde
