### ISSUE TITLE
Lag from components

### ISSUE THREAD

**Issue by Firigion** [StorageTechDictionary/StorageTechDictionary.github.io#5]
Raff proposed an entry for lag from different redstone components: https://discord.com/channels/748542142347083868/811675089133240330/811677443882614807

I dont' think this would be appropiate as an entry.

**Comment by JoakimThorsen** [comment]
agree, though a super novice-level explanation of "lag" could be a good idea. Make a distinction between fps and tps and mentioning mspt at least?

**Comment by MeMeBallJM** [comment]
> agree, though a super novice-level explanation of "lag" could be a good idea. Make a distinction between fps and tps and mentioning mspt at least?

Maybe just define TPS, MSPT, FPS if not already defined.
