### ISSUE TITLE
toggle state, stateless

### ISSUE THREAD

**Issue by Firigion** [StorageTechDictionary/StorageTechDictionary.github.io#9]
Merge the two toggle state entries. probably give some palce to the discussion regarding whne or why they are bad. Also add **stateless**, maybe to the sold state. I ahte this discussion >_<

**Comment by JoakimThorsen** [comment]
the current "togglestate" entry claims togglestates are never resettable, implying that that would instead be a "latch," though I don't think that's accurate regarding how people actually use it, given that terms like "self-resetting togglestates" aren't uncommon

**Comment by Firigion** [comment]
More on stateless (thread and comments outside it): https://discord.com/channels/748542142347083868/811675089133240330/908568100344062023

**Comment by Firigion** [comment]
And more... https://discord.com/channels/748542142347083868/811675089133240330/945053898228523099

> **Stateless [ambiguous] **
> Can mean:
> 
> - No piston spitting (some exclude self-resetting piston spit behavior)
> - No stored state (some exclude self-resetting state)
>  
> **State**
> - Persistent information from prior interaction

**Comment by MeMeBallJM** [comment]
> the current "togglestate" entry claims togglestates are never resettable, implying that that would instead be a "latch," though I don't think that's accurate regarding how people actually use it, given that terms like "self-resetting togglestates" aren't uncommon

I agree it's nonsensical to say toggle states are never resettable.
